#personal-setting-netty
netty:
  port: 8888

#datasource
spring:
  #livereload port
  devtools:
    livereload:
      port: 35730

  redis:
    port: 6379
    host:
    database: 0
    password:

#rocketmq
rocketmq:
  name-server:
  producer:
    group:






























#  main:
#    allow-bean-definition-overriding: true